### ISSUE TITLE
配列の変数名は複数形にすることが多いです

### ISSUE THREAD

**Issue by amapyon** [program2017ry/pg_ex11#2]
https://github.com/program2017ry/pg_ex11/blob/afcde7be76ee0de097d00a5c4a207e45a0adb2ee/src/ex0906/SelectGreeting.java#L5

テキストでは「message」ですが、
配列なので「messages」とする方が、変数名の付け方としては多数派です。

**Comment by program2017ry** [comment]
コメントありがとうございます。修正しました。
勉強になります！
