### ISSUE TITLE
publicとthisについて

### ISSUE THREAD

**Issue by program2017ry** [program2017ry/pg_ex11#7]
https://github.com/program2017ry/pg_ex11/blob/934746401757ddb02c70c5be7afb71c2be49f1c1/src/ex1002/Rectangle.java#L10-L12
@amapyon

細かい話ですが、toString内で、アクセス制御をpublicにしておくべきか、フィールドにthisをつけるべきかはどっちでもいいのかなと考えているのですが、これはつけるべきとかつけないべきとかあるのでしょうか。

**Comment by amapyon** [comment]
@program2017ry 

# toString() に publicをつけるか
toString() メソッドは、Javaの最も基本のクラスであるObjectクラスにある、toString()メソッドをオーバーライドしています。
そのため、ObjectクラスのtoString()と同じ可視性のpublicを付ける必要があります。

https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#toString--

# フィールドをアクセスする際にthisをつけるか
厳密なルールはありません。
thisは省略するほうが多数派です。

**Comment by program2017ry** [comment]
ご回答ありがとうございます。承知しました。
